import { useState, useMemo, useEffect, useRef, useCallback } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import rehypeRaw from 'rehype-raw'
import mermaid from 'mermaid'
import type { Components } from 'react-markdown'

// ─── Mermaid Setup ───

mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  fontFamily: 'Plus Jakarta Sans, sans-serif',
})

function MermaidDiagram({ chart }: { chart: string }) {
  const [svg, setSvg] = useState('')

  useEffect(() => {
    const id = `m-${Date.now()}-${Math.random().toString(36).slice(2)}`
    // Content is from local markdown files only — trusted source
    mermaid
      .render(id, chart)
      .then(({ svg: renderedSvg }) => setSvg(renderedSvg))
      .catch(() => setSvg(''))
  }, [chart])

  if (!svg) return <pre><code>{chart}</code></pre>
  // Safe: SVG is generated by mermaid from our own local markdown content
  return <div className="mermaid-diagram" dangerouslySetInnerHTML={{ __html: svg }} />
}

// ─── Types ───

interface FileEntry {
  path: string
  name: string
  content: string
}

interface Section {
  key: string
  title: string
  description: string
  color: string
  files: FileEntry[]
}

interface Heading {
  level: number
  text: string
  id: string
}

// ─── Markdown Imports ───

const componentMds = import.meta.glob('../../components/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const deepDiveMds = import.meta.glob('../../deep_dives/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const domainMds = import.meta.glob('../../domains/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const assessmentMds = import.meta.glob('../../assessments/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

// ─── Helpers ───

function toDisplayName(path: string): string {
  const fileName = path.split('/').pop()?.replace('.md', '') || ''
  return fileName
    .split(/[_-]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function parseFiles(
  mds: Record<string, string>,
  order?: string[],
): FileEntry[] {
  const entries = Object.entries(mds).map(([path, content]) => ({
    path,
    name: toDisplayName(path),
    content,
  }))
  if (order) {
    const orderMap = new Map(order.map((name, i) => [name.toLowerCase(), i]))
    return entries.sort((a, b) => {
      const ai = orderMap.get(a.name.toLowerCase()) ?? 999
      const bi = orderMap.get(b.name.toLowerCase()) ?? 999
      return ai - bi
    })
  }
  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim()
}

function extractHeadings(markdown: string): Heading[] {
  const regex = /^(#{1,3})\s+(.+)$/gm
  const headings: Heading[] = []
  let match
  while ((match = regex.exec(markdown)) !== null) {
    const text = match[2]
      .replace(/\*\*/g, '')
      .replace(/`/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    headings.push({ level: match[1].length, text, id: slugify(text) })
  }
  return headings
}

function getTextContent(node: React.ReactNode): string {
  if (typeof node === 'string') return node
  if (typeof node === 'number') return String(node)
  if (Array.isArray(node)) return node.map(getTextContent).join('')
  if (node && typeof node === 'object' && 'props' in node) {
    return getTextContent((node as any).props.children)
  }
  return ''
}

// ─── Table of Contents ───

function TableOfContents({
  headings,
  activeId,
}: {
  headings: Heading[]
  activeId: string
}) {
  const filtered = headings.filter((h) => h.level <= 3)
  if (filtered.length === 0) return null

  return (
    <div className="toc">
      <h3 className="toc-title">On This Page</h3>
      <ul className="toc-list">
        {filtered.map((h, i) => (
          <li key={`${h.id}-${i}`}>
            <a
              href={`#${h.id}`}
              onClick={(e) => {
                e.preventDefault()
                document
                  .getElementById(h.id)
                  ?.scrollIntoView({ behavior: 'smooth', block: 'start' })
              }}
              className={`toc-link toc-level-${h.level} ${
                activeId === h.id ? 'toc-active' : ''
              }`}
            >
              {h.text}
            </a>
          </li>
        ))}
      </ul>
    </div>
  )
}

// ─── App ───

export default function App() {
  const [selected, setSelected] = useState<FileEntry | null>(null)
  const [activeHeadingId, setActiveHeadingId] = useState('')
  const mainRef = useRef<HTMLElement>(null)

  // Recommended reading order: fundamentals → building blocks → resilience
  const componentOrder = [
    'Networking',
    'Database',
    'Cache',
    'Scalability',
    'Load Balancer',
    'Message Queue',
    'Api Design',
    'Rate Limiter',
    'Fault Tolerance',
    'Consistency And Consensus',
  ]

  const sections: Section[] = useMemo(
    () => [
      {
        key: 'components',
        title: 'Components',
        description: 'Trade-off comparisons',
        color: 'var(--accent)',
        files: parseFiles(componentMds, componentOrder),
      },
      {
        key: 'domains',
        title: 'Domains',
        description: 'Industry-specific patterns',
        color: 'var(--accent-orange)',
        files: parseFiles(domainMds),
      },
      {
        key: 'deep_dives',
        title: 'Deep Dives',
        description: 'Architecture case studies',
        color: 'var(--accent-blue)',
        files: parseFiles(deepDiveMds),
      },
      {
        key: 'assessments',
        title: 'Assessments',
        description: 'Blind spot tracking',
        color: 'var(--accent-green)',
        files: parseFiles(assessmentMds),
      },
    ],
    [],
  )

  const allFiles = useMemo(() => sections.flatMap((s) => s.files), [sections])

  const headings = useMemo(
    () => (selected ? extractHeadings(selected.content) : []),
    [selected],
  )

  useEffect(() => {
    if (!selected || headings.length === 0) return

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries.find((e) => e.isIntersecting)
        if (visible) setActiveHeadingId(visible.target.id)
      },
      { rootMargin: '-60px 0px -75% 0px', root: mainRef.current },
    )

    const timer = setTimeout(() => {
      headings.forEach(({ id }) => {
        const el = document.getElementById(id)
        if (el) observer.observe(el)
      })
    }, 80)

    return () => {
      clearTimeout(timer)
      observer.disconnect()
    }
  }, [selected, headings])

  useEffect(() => {
    mainRef.current?.scrollTo({ top: 0 })
    setActiveHeadingId('')
  }, [selected])

  const mdComponents: Components = useMemo(
    () => ({
      h1: ({ children, ...props }: any) => (
        <h1 id={slugify(getTextContent(children))} {...props}>
          {children}
        </h1>
      ),
      h2: ({ children, ...props }: any) => (
        <h2 id={slugify(getTextContent(children))} {...props}>
          {children}
        </h2>
      ),
      h3: ({ children, ...props }: any) => (
        <h3 id={slugify(getTextContent(children))} {...props}>
          {children}
        </h3>
      ),
      table: ({ children, ...props }: any) => (
        <div className="table-wrapper">
          <table {...props}>{children}</table>
        </div>
      ),
      pre: ({ children, ...props }: any) => {
        const child = Array.isArray(children) ? children[0] : children
        if (child?.props?.className === 'language-mermaid') {
          return (
            <MermaidDiagram
              chart={String(child.props.children).replace(/\n$/, '')}
            />
          )
        }
        return <pre {...props}>{children}</pre>
      },
    }),
    [],
  )

  const handleSelect = useCallback((file: FileEntry) => {
    setSelected(file)
  }, [])

  return (
    <div className="app-layout">
      <aside className="sidebar">
        <div className="sidebar-header">
          <button
            onClick={() => setSelected(null)}
            className="sidebar-title-btn"
          >
            <span className="sidebar-title">System Design</span>
            <span className="sidebar-subtitle">Tutor</span>
          </button>
          <span className="sidebar-count">{allFiles.length} notes</span>
        </div>

        <nav className="sidebar-nav">
          {sections.map((s) => (
            <div key={s.key} className="sidebar-section">
              <div className="sidebar-section-header">
                <span
                  className="sidebar-dot"
                  style={{ background: s.color, color: s.color }}
                />
                <span className="sidebar-section-title">{s.title}</span>
              </div>
              {s.files.length === 0 ? (
                <p className="sidebar-empty">No notes yet</p>
              ) : (
                <ul>
                  {s.files.map((f) => (
                    <li key={f.path}>
                      <button
                        onClick={() => handleSelect(f)}
                        className={`sidebar-item ${
                          selected?.path === f.path ? 'sidebar-item-active' : ''
                        }`}
                        style={
                          selected?.path === f.path
                            ? ({ borderLeftColor: s.color } as any)
                            : undefined
                        }
                      >
                        {f.name}
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </nav>
      </aside>

      <main className="main-content" ref={mainRef}>
        {selected ? (
          <div className="article-layout">
            <div className="article-container">
              <div className="breadcrumb">
                <button
                  onClick={() => setSelected(null)}
                  className="breadcrumb-home"
                >
                  Home
                </button>
                <span className="breadcrumb-sep">/</span>
                <span className="breadcrumb-current">{selected.name}</span>
              </div>
              <article className="article-content">
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  rehypePlugins={[rehypeRaw]}
                  components={mdComponents}
                >
                  {selected.content}
                </ReactMarkdown>
              </article>
            </div>
            <TableOfContents headings={headings} activeId={activeHeadingId} />
          </div>
        ) : (
          <div className="home">
            <div className="home-header">
              <h1 className="home-title">
                System Design{' '}
                <span className="home-title-accent">Tutor</span>
              </h1>
              <p className="home-desc">
                Your personal knowledge base for mastering distributed system
                design.
              </p>
            </div>
            <div className="home-grid">
              {sections.map((s) => (
                <div key={s.key} className="home-card">
                  <div
                    className="home-card-accent"
                    style={{ background: s.color }}
                  />
                  <div className="home-card-header">
                    <h2 className="home-card-title">{s.title}</h2>
                    <span className="home-card-count">{s.files.length}</span>
                  </div>
                  <p className="home-card-desc">{s.description}</p>
                  {s.files.length > 0 ? (
                    <ul className="home-card-list">
                      {s.files.map((f) => (
                        <li key={f.path}>
                          <button
                            onClick={() => handleSelect(f)}
                            className="home-card-link"
                          >
                            {f.name}
                          </button>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="home-card-empty">
                      No notes yet. Start a discussion to generate content.
                    </p>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
